### PR TITLE
Fix main file path

### PR DESCRIPTION
**Pull request by lessless**
Looks like main file now resides in the `dist` folder

### CODE REVIEW

**Comment by kyrylo** [comment]
Hi! Are you experiencing issues with it? The reason I'm asking is because we amended it to `lib` [just yesterday](https://github.com/airbrake/airbrake-js/commit/86f9825d527ea107f3d4a853a9d5a8645628986e).

**Comment by vmihailenco** [comment]
I am inclined to say LGTM, but @lessless which tool do you use with bower? wiredep? AFAIK:
- wiredep requires dist/client.js
- requireJs wants lib/client.js

And I don't know how to make both of them happy.

**Comment by lessless** [comment]
@vmihailenco @kyrylo  We are using `airbrake-js` as a dependency on our own bower package

**Comment by vmihailenco** [comment]
Yeah, the question is how you include airbrake-js into your app? Do you use some tool like wiredep or browserify?

**Comment by lessless** [comment]
It's included as the

**Comment by lessless** [comment]
Whoops, that was  accidentialy. Let ne ask someone from the frontend team to answer your question.

**Comment by kyrylo** [comment]
@lessless nice job! Eagle eye :bird:

**Pull request merged**
