### PR TITLE
Add stacktracejs backend.

### PR DESCRIPTION
**Pull request by vmihailenco**
Updates https://github.com/airbrake/airbrake-js/issues/220

### CODE REVIEW

**Comment by kyrylo** [comment]
Why do we have to have 2 backtrace parsers? Given that we integrate this one, when will [stack.coffee](https://github.com/airbrake/airbrake-js/blob/e55f31a0e9360650ad620a6f38763c28b72dc2d6/src/processors/stack.coffee) be useful?

**Comment by vmihailenco** [comment]
I'd like to remove stack.coffee, but we have ability to write custom processors and custom reporters so we can keep both.

**Comment by kyrylo** [comment]
The ability to write custom processors is not even documented, so I would guess nobody even uses it. We need to have at least some documentation to justify this PR. Perfect documentation would explain why I want to specify anything other than the default (which you don't even have to specify).

**Comment by vmihailenco** [comment]
I thought I just said that I'd like to remove stack.coffee, not write documentation about it.

**Comment by kyrylo** [comment]
Okay, I didn't get this part then:

> [...] but we have ability to write custom processors and custom reporters so we can keep both.

Do you plan to remove `opts.processor` altogether?

**Comment by vmihailenco** [comment]
Why? It is there, it is working, it is not documented and none complains. What is the problem?

I just want to make stacktrackejs to be the default backtrace processor.

**Pull request merged**
