### PR TITLE
Use browser native promise where possible

### PR DESCRIPTION
**Pull request by vmihailenco**
Fixes https://github.com/airbrake/airbrake-js/issues/407

### CODE REVIEW

**Comment by RandomSeeded** [comment]
@vmihailenco do you think this is ready to be released as `1.0.8`? We'd like to pull it in :)

**Comment by vmihailenco** [comment]
There are still some issues with webpack 4.x config and [promise-polyfil](https://github.com/taylorhakes/promise-polyfill/pull/78), but I hope to release it this week.

**Comment by vmihailenco** [comment]
Releaded v1.1.0

**Comment by dreyks** [comment]
how does this uses browser native promise where possible? 
https://github.com/airbrake/airbrake-js/blob/94077a7e1614ab95a5b257841ba145dbbe334a00/src/client.ts#L1
just overwrites the global window.Promise as specified in [promise-polyfill doc](https://www.npmjs.com/package/promise-polyfill#simple-use). It is also stated that library authors must NOT use this method

**Comment by dreyks** [comment]
Oh wait, nevermind, their doc is actually wrong since it does not overwrite global Promise if it's already there
https://github.com/taylorhakes/promise-polyfill/blob/487e452eea264dbbf7625591cc34ee3dab128419/src/polyfill.js#L20-L24

**Pull request merged**
