### PR TITLE
Sample fix for uncaught exception handler causing hangs

### PR DESCRIPTION
**Pull request by RandomSeeded**
Hi,

I'm afraid there's an error with the uncaught exception handler code. 

Inside `historian.ts`:

```
        return new MyPromise().resolve(null);
```

However, because we are resolving with null and checking resolution with a truthy check, that causes the checker within `finally` to believe that the promise has not already been resolved, even though it has. A sample fix (promise.ts:76) is provided in this pr.

### CODE REVIEW

**Comment by RandomSeeded** [comment]
screen shot 2018-03-05 at 9 50 51 am

Behavior from master (note the hang forcing the process kill)

**Comment by RandomSeeded** [comment]
screen shot 2018-03-05 at 9 51 31 am

Behavior on this branch

**Comment by RandomSeeded** [comment]
Also this is clearly up to you, but given that the promise polyfill is now pretty fully-featured, it might make sense to just take one from a third party that's been thoroughly built out and tested.

Thanks
-Nate

**Comment by vmihailenco** [comment]
Thanks for the report.

>it might make sense to just take one from a third party that's been thoroughly built out and tested.

Last time I checked the size of fully-featured and battle tested promise implementation was bigger than this library.

**Pull request closed without merging**
