### PR TITLE
Feature/support api proxy in client lib

### PR DESCRIPTION
**Pull request by andrii-melnyk-ring**

### CODE REVIEW

**Comment by andrii-melnyk-ring** [comment]
fixes #525

**Comment by andrii-melnyk-ring** [comment]
Hi @vmihailenco do you have any comments regarding API change, is does it looks good? Do you have any comments?

**Comment by tuusberg** [comment]
What is the resolution on this one? We're facing exactly the same issue here and having that functionality built into `airbrake-js` would help a lot.

**Comment by vmihailenco** [comment]
As I understand you can achieve roughly the same with following config:

```
var airbrake = new airbrakeJs.Client({
  projectId: 1,
  projectKey: 'YOUR_CUSTOM_TOKEN',
  environment: 'production',
  host: 'https://airbrake-proxy.your-domain.com',
});
```

With this PR you can also change API endpoints, but that should not be important.

And while this PR is well-written and relatively small the amount of people that will be using it is neglectable. Not many users are ready to write a custom proxy server to hide an API key...

**Pull request closed without merging**
