### PR TITLE
Send errors to the /notices endpoint instead of /create-notice

### LINKED ISSUE #213: wrong url
According to the airbrake api (https://airbrake.io/docs/api/#error-notification-v3) the url form creating notifications should be:
POST https://airbrake.io/api/v3/projects/PROJECT_ID/notices?key=PROJECT_KEY

but the plugin generates url with this format:

POST https://airbrake.io/api/v3/projects/PROJECT_ID/create-notice?key=PROJECT_KEY

which works well with aibrake service but it's not working with other services supporting the api.

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #213 (wrong url)

### CODE REVIEW

**Comment by vmihailenco** [comment]
Did you test that old URL does not work?

**Comment by kyrylo** [comment]
`create-notice` works, but why would we use undocumented endpoint?

**Comment by vmihailenco** [comment]
Does it cause any issues?

**Comment by kyrylo** [comment]
I didn't notice any.

**Comment by kyrylo** [comment]
Do you have any objections?

**Comment by vmihailenco** [comment]
If you ask about this PR then I think it should be closed because I don't see what it fixes.

**Comment by kyrylo** [comment]
I assume it fixes Errbit compatibility, since it is based on our documentation.
It would be nice to use our own documentation for our notifiers.

**Comment by vmihailenco** [comment]
Cool, you can document that endpoint then.

**Comment by davorpeic** [comment]
I see that this wasn't merged in the latest version, this issue maybe is not causing issues with airbrake service, but I get 'invalid controller' error as this endpoint doesn't exist in third party services using airbrake js client. Workaround is to rename manually /create-notice to /notices.

**Comment by vmihailenco** [comment]
I explained how you can configure notifier to work with errbit - https://github.com/airbrake/airbrake-js/issues/213#issuecomment-263531096. Probably errbit users should add it to the readme or errbit docs...

**Comment by davorpeic** [comment]
@vmihailenco hey, thanks, yeah, I tried that first `(reporter: 'xhr')` but I get xhr error from the server, not sure if not configured to receive this kind of post or what, but it is not working so I renamed endpoints.

**Comment by vmihailenco** [comment]
Okay, I see. Probably we should add another reporter for errbit users then.

**Comment by kyrylo** [comment]
Why do we support `/create-notice` in the first place?

**Comment by vmihailenco** [comment]
See "Simple requests" in https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS. Such simple requests require only 1 client-server round-trip instead of 2 with normal/non-simple CORS requests.

**Comment by vmihailenco** [comment]
Closing. Even if this is needed it should be done by creating new reporter in https://github.com/airbrake/airbrake-js/tree/master/src/reporters

**Pull request closed without merging**
