### PR TITLE
Allow the removal of uncaught exception and unhandled rejection handlers from historian

### PR DESCRIPTION
**Pull request by RandomSeeded**
This handles https://github.com/airbrake/airbrake-js/issues/389

In regards to https://github.com/airbrake/airbrake-js/pull/391, I'd recommend this PR over just logging because we want to maintain the behavior of a node process without an uncaught exception handler crashing on errors instead of hanging. 

A real-world example of this is a shell script which invokes a node script; on error we would expect the node process to exit and that failure to be propagated to the shell script to handle (or crash itself).

### CODE REVIEW

**Comment by RandomSeeded** [comment]
Example usage (removes handlers for our scripts directory):

if (/dist\/scripts/.test(require.main.filename)) {
  airbrake.ignoreUncaughtExceptions();
  airbrake.ignoreUnhandledRejections();
}

**Comment by vmihailenco** [comment]
I did not try, but can't you achieve the same with:

```
process.on('uncaughtException', function(err) {
    throw err;
});
```

in your app after airbrake-js is loaded?

**Comment by RandomSeeded** [comment]
You can, but IMO it's not the best approach; that code is dangerous in that if there ever were other uncaught exception handlers, you've now taken what should be a gracefully-handled error and instead turned it into a hard crash. I would not want to put it in common code, and so the burden would instead be on the writer of every single script to know that a) their script required `airbrake-js` (possibly indirectly) b) that this could cause unexpected hangs on errors and c) how to correctly handle this behavior

Additionally, I think that from a consumer perspective there should definitely be a clear API for disabling this functionality. Having the `uncaughtException` handler be automatically added (in contrast to the behavior of `node-airbrake`, which required it to be explicitly added via `handleExceptions`) is changing the behavior of the consumer's environment. I can understand the desire to have this be enabled by default, but I think at minimum a well-documented ability to disable this functionality would be good.

Possibly the most ideal fix would be to not add the `unhandledException` handlers until the first time a client is initialized. @vmihailenco thoughts on that?

**Comment by vmihailenco** [comment]
>you've now taken what should be a gracefully-handled error and instead turned it into a hard crash

I don't follow - that code just re-throws an exception so app crashes just like you suggested. How that breaks gracefully-handled error case?

>Possibly the most ideal fix would be to not add the unhandledException handlers until the first time a client is initialized

Sure, if that makes things better for you - why not.

**Comment by RandomSeeded** [comment]
`process.on('uncaughtException', e => throw e)` does work correctly for scripts that don't have any other uncaught exception handlers.

The issue would be that if you did have any other uncaught exception handlers, that snippet is a truly bad idea. In our case, we have common code used by both our scripts and longer-running node service. That exception handler could not be added to any code used by our longer-running service; the thrown exception from within an uncaught exception handler could cause the immediate shutdown of our service on error instead of a graceful shutdown.

I'll create a PR for the delayed addition of the uncaught exception handlers. Thanks for the quick responses.

**Pull request closed without merging**
